<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-03-26T22:02:26 IST" name="Suite" finished-at="2022-03-26T22:03:24 IST" duration-ms="58261">
    <groups>
    </groups>
    <test started-at="2022-03-26T22:02:26 IST" name="Test" finished-at="2022-03-26T22:03:24 IST" duration-ms="58261">
      <class name="testcases2.Logintest">
        <test-method is-config="true" signature="DataSetUP()[pri:0, instance:testcases2.Logintest@16a0ee18]" started-at="2022-03-26T22:02:26 IST" name="DataSetUP" finished-at="2022-03-26T22:02:27 IST" duration-ms="1068" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DataSetUP -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:testcases2.Logintest@16a0ee18]" started-at="2022-03-26T22:02:27 IST" name="setup" finished-at="2022-03-26T22:03:00 IST" duration-ms="33113" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases2.Logintest.LoginFailiureTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="LoginFailiureTest()[pri:0, instance:testcases2.Logintest@16a0ee18]" started-at="2022-03-26T22:03:00 IST" name="LoginFailiureTest" finished-at="2022-03-26T22:03:03 IST" duration-ms="2740" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid Credentials expected [Epic sadface: Username and password do not match any user in this service.] but found [Epic sadface: Username and password do not match any user in this service]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid Credentials expected [Epic sadface: Username and password do not match any user in this service.] but found [Epic sadface: Username and password do not match any user in this service]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at testcases2.Logintest.LoginFailiureTest(Logintest.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFailiureTest -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:testcases2.Logintest@16a0ee18]" started-at="2022-03-26T22:03:03 IST" name="TearDown" finished-at="2022-03-26T22:03:05 IST" duration-ms="2349" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:testcases2.Logintest@16a0ee18]" started-at="2022-03-26T22:03:05 IST" name="setup" finished-at="2022-03-26T22:03:14 IST" duration-ms="9085" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases2.Logintest.LoginSuccessTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="LoginSuccessTest()[pri:0, instance:testcases2.Logintest@16a0ee18]" started-at="2022-03-26T22:03:14 IST" name="LoginSuccessTest" finished-at="2022-03-26T22:03:15 IST" duration-ms="340" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginSuccessTest -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:testcases2.Logintest@16a0ee18]" started-at="2022-03-26T22:03:15 IST" name="TearDown" finished-at="2022-03-26T22:03:15 IST" duration-ms="452" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:testcases2.Logintest@16a0ee18]" started-at="2022-03-26T22:03:15 IST" name="setup" finished-at="2022-03-26T22:03:22 IST" duration-ms="6862" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases2.Logintest.LoginSuccessTestExternalDataTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="LoginSuccessTestExternalDataTest()[pri:0, instance:testcases2.Logintest@16a0ee18]" started-at="2022-03-26T22:03:22 IST" name="LoginSuccessTestExternalDataTest" finished-at="2022-03-26T22:03:23 IST" duration-ms="1137" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginSuccessTestExternalDataTest -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:testcases2.Logintest@16a0ee18]" started-at="2022-03-26T22:03:23 IST" name="TearDown" finished-at="2022-03-26T22:03:23 IST" duration-ms="470" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="DataTearDown()[pri:0, instance:testcases2.Logintest@16a0ee18]" started-at="2022-03-26T22:03:23 IST" name="DataTearDown" finished-at="2022-03-26T22:03:24 IST" duration-ms="568" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DataTearDown -->
      </class> <!-- testcases2.Logintest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
